### ISSUE TITLE
Sample code "How to use this libraly"

### ISSUE THREAD

**Issue by Andrzej1991** [bkhezry/MapDrawingTools#1]
Hello, i try use your libraly into my project and i cant configure it.. Can you create any sample code?

**Comment by bkhezry** [comment]
Hi,
you can use this sample code that provides in the app folder
[MainActivity](https://github.com/bkhezry/MapDrawingTools/blob/master/app/src/main/java/com/github/bkhezry/demomapdrawingtools/ui/MainActivity.java)
