### ISSUE TITLE
App crashes when lunching MapsActivity

### ISSUE THREAD

**Issue by ClaudeHangui** [bkhezry/MapDrawingTools#2]
I added the MapsActivity in the manifest, defined the style as recommended
<item name="windowActionBar">false</item>
<item name="windowNoTitle">true</item>

Here is my activity class:

public class MyMap extends AppCompatActivity
{
    private static final int REQUEST_CODE = 1;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_another_map);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (resultCode == RESULT_OK && requestCode == REQUEST_CODE && data != null) {
            DataModel dataModel =
                    data.getExtras().getParcelable(MapsActivity.POINTS);
            LatLng[] points = dataModel.getPoints();
        }
    }

    public void TryMe(View view) {
        DrawingOption.DrawingType currentDrawingType = DrawingOption.DrawingType.POLYGON;
        Intent intent =
                new DrawingOptionBuilder()
                        .withLocation(35.744502, 51.368966)
                        .withMapZoom(14)
                        .withFillColor(Color.argb(60, 0, 0, 255))
                        .withStrokeColor(Color.argb(100, 255, 0, 0))
                        .withStrokeWidth(3)
                        .withRequestGPSEnabling(false)
                        .withDrawingType(currentDrawingType)
                        .build(getApplicationContext());
        startActivityForResult(intent, REQUEST_CODE);
    }
}

When I click the button in my layout file to open your MapsActivity I get a crash......Here is what I have in my logcat:
java.lang.RuntimeException: Unable to start activity
 Caused by: java.lang.NullPointerException at com.github.bkhezry.mapdrawingtools.ui.MapsActivity.setUpFABs(MapsActivity.java:106)
  at com.github.bkhezry.mapdrawingtools.ui.MapsActivity.onCreate(MapsActivity.java:96)

**Comment by bkhezry** [comment]
Hi @ClaudeHangui.
I am sorry for the delay in responding.
I checked the library and not found this error. just released my source code of test library in this URL:
https://github.com/bkhezry/TestDrawingTools

**Comment by ClaudeHangui** [comment]
Yup....I tested it now it works !!
Thanks for the heads up 👍

**Comment by snowman69** [comment]
hi @bkhezry 
I have same problem and that link not works any more
همه چیو کپی کردم اما بازم کرش میکنه

**Comment by bkhezry** [comment]
@snowman69 Please send logcat error here.

**Comment by snowman69** [comment]
solved! 
just missing this line:
implementation 'com.google.android.gms:play-services-location:16.0.0'
